### PR TITLE
Added BPM writing support

### PR DESCRIPTION
**Pull request by FMS-Cat**
Added BPM writing support.
I have no knowledge about both TagLib and C++ and this is super simple code modification.
Please merge it if you don't care!

### CODE REVIEW

**Comment by 0x00A** [comment]
+1 for this, can you add a simple test for this? happy to merge!

**Comment by FMS-Cat** [comment]
Okay, test is even my first experience...

Ooops, there is already test for bpm!
But this test overwrites already existed tags and passes even if bpm writing is not implemented...

**Comment by FMS-Cat** [comment]
I'm going to reimplement the test.
Copy the mp3 thats tags is initially blank to tmp and then write some tags

**Comment by FMS-Cat** [comment]
No no no, I just need to apply `rn` to bpm field

**Comment by 0x00A** [comment]
Cool if it passes CI, i'll merge

**Comment by FMS-Cat** [comment]
passed ✓

**Comment by 0x00A** [comment]
Published to npm as `taglib2@2.8.0`. 🎉

**Comment by FMS-Cat** [comment]
Thanks! :pray:

**Pull request merged**
