### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by bobek-balinek**
Hi there,

This pull request fixes the failing Windows builds and provides changes in the CMake script to directly pull source code from TagLib's git repository.

#### Summary:

1. Changed the NODE_MODULE initialiser to have 3 arguments due to the `node::addon_register_func` errors.
2. Switched to use `ExternalProject` module and include TagLib through `add_dependencies` to fix fatal errors `unresolved external symbol __declspec(dllimport)`.
3. Moved the `ELECTRON` env check to a node script for cross-platform compatibility (`$ELECTRON` isnt recognised on Windows as it expects `%ELECTRON%` instead).
4. Removed the TagLib's source in `lib/taglib-31f3109` as it's redundant at this point.
5. Added Travis configuration

#### Builds tested on:

- Windows 10 32/64bit (Visual Studio 14 2015) (Manual & Appveyor)
- OSX El Captain 10.11.6 (LLVM version 7.3.0)
- Ubuntu 14 through Travis

### CODE REVIEW

**Comment by 0x00A** [comment]
The fix for travis-ci might be really simple, it looks like a tweak to the config file maybe?

```
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables. If you require sudo, add 'sudo: required' to your .travis.yml
```

**Comment by bobek-balinek** [comment]
It's actually missing a config file (`.travis.yml` isn't checked into the repository) - I'll add it later today.

**Comment by bobek-balinek** [comment]
@simon-p-r good point on appveyor, I'll add that too.

**Comment by simon-p-r** [comment]
Here is a sample appveyor yaml [file](https://github.com/simon-p-r/node-taglib2/blob/windows-build/appveyor.yml)

**Comment by bobek-balinek** [comment]
So I got a green build on Appveyor and Travis except…

```text
node --version && npm --version
v6.6.0
3.10.7
npm test # PowerShell
> taglib2@2.5.15 test C:\projects\node-taglib2
> tape ./tests
TAP version 13
# setup
# sync write/read
ok 1 should be truthy
ok 2 should be truthy
ok 3 not enough arguments
ok 4 should be truthy
ok 5 not enough arguments
ok 6 should be equal
ok 7 should be equal
ok 8 should be equal
not ok 9 should be equal
  ---
    operator: equal
    expected: 120
    actual:   1202
  ...
ok 10 should be equal
ok 11 should be equal
ok 12 should be equal
ok 13 should be equal
ok 14 should be equal
ok 15 should be equal
ok 16 should be equal
ok 17 should be equal
ok 18 should be equal
ok 19 should be equal
ok 20 should be equal
ok 21 should be equal
ok 22 should be equal
# sync write/read m4a + jpg
# write a copy of an mp4 file with a new image
# read the tags from the new file
# write the picture to a tmp file
# compare the image extracted to the image added
ok 23 should be equal
# sync write/read m4a + png
# write a copy of an mp4 file with a new image
# read the tags from the new file
# write
```

The BPM values jump between `120`, `1201` and `1202`. Have you come across this before @0x00A?

**Comment by 0x00A** [comment]
@bobek-balinek strange, i've never seen that. at first it looks like it is concatenating something. but the assertion is just `assert.equal(tags.bpm, 120)`. Not much of a test but i guess at least it tells us taglib can parse `bpm` tags.

**Comment by bobek-balinek** [comment]
That's sorted then, both Travis and Appveyor builds have passed. Can you set up an account for Appveyor for the whole repository though? I was using my own, branch-specific configuration, thanks!

**Comment by 0x00A** [comment]
Ok, set up, the appveyor webhook looks like it's reporting a valid configuration. I will test on osx and then if that goes well we should be able to merge!

**Comment by 0x00A** [comment]
Tests pass on macOS. I'm going to merge this. I'll run our UI automation tests and if that goes well, I'll make a windows build. Everything looks good so far.

**Pull request merged**
